# Generated by Django 4.1.3 on 2023-04-01 18:01

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_submission_deadline"),
    ]

    operations = [
        migrations.AlterField(
            model_name="context",
            name="code",
            field=models.SlugField(
                max_length=32,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        re.compile("[a-z_][a-z_\\-\\/0-9]+", 2)
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="username",
            field=models.SlugField(
                max_length=32,
                validators=[
                    django.core.validators.RegexValidator(
                        re.compile("[a-z_][a-z_\\.0-9]+", 2)
                    )
                ],
            ),
        ),
    ]
