# Generated by Django 4.1.3 on 2023-04-01 22:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_alter_context_code_alter_student_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="exercise",
            name="template",
            field=models.TextField(
                default="", help_text="Plantilla de ejemplo para el alumno"
            ),
        ),
    ]
