# Generated by Django 4.1.3 on 2023-04-01 23:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_exercise_template"),
    ]

    operations = [
        migrations.AddField(
            model_name="exercise",
            name="title",
            field=models.CharField(
                default="Falta título", help_text="Título del ejercicio", max_length=128
            ),
        ),
    ]
