# Generated by Django 4.1.3 on 2023-04-01 23:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0011_exercise_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="exercise",
            name="description",
            field=models.TextField(
                default="Falta descripción",
                help_text="Explicaciones adicionales del ejercicio",
            ),
        ),
    ]
