# Generated by Django 4.1.3 on 2023-04-23 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0012_exercise_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="Guard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "logic",
                    models.CharField(
                        help_text="Nombre del _callable_ responsable", max_length=64
                    ),
                ),
                (
                    "params",
                    models.CharField(
                        help_text="Parámetros necesarios para la lógica, si fueran necesarios, en formato JSON.",
                        max_length=64,
                    ),
                ),
                ("description", models.TextField()),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="guards",
                        to="core.exercise",
                    ),
                ),
            ],
        ),
    ]
