# Generated by Django 4.1.3 on 2023-04-23 12:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0013_guard"),
    ]

    operations = [
        migrations.AddField(
            model_name="exercise",
            name="asserts",
            field=models.TextField(
                default="", help_text="Asserts que debe pasar el código"
            ),
        ),
    ]
