# Generated by Django 4.1.3 on 2023-03-18 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='El nombre del logro, p.e. `List master`.', max_length=128, unique=True)),
                ('description', models.TextField(help_text='Descripción del reto, por ejemplo, resolver al menos 20 ejercicios del tema Listas.')),
                ('symbol', models.CharField(help_text='Representación simbólica del logro (Se puede usar unicode). Por ejemplo ♔⛁.', max_length=16, unique=True)),
                ('logic', models.CharField(help_text='Nombre del _callable_ responsable de verificar el cumplimiento del reto.', max_length=64)),
                ('params', models.CharField(help_text='Parámetros necesarios para la lógica, se fueran necesarios, en formato JSON', max_length=64)),
            ],
        ),
    ]
