# Generated by Django 4.1.3 on 2023-03-18 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_submission_deadline'),
        ('badges', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='params',
            field=models.CharField(help_text='Parámetros necesarios para la lógica, si fueran necesarios, en formato JSON.', max_length=64),
        ),
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('granted_at', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora en que soe logró el badge.')),
                ('achievement', models.ForeignKey(help_text='El logro completado por el que se obtuvo el badge.', on_delete=django.db.models.deletion.PROTECT, related_name='badges', to='badges.achievement')),
                ('student', models.ForeignKey(help_text='El estudiante que posee el badge.', on_delete=django.db.models.deletion.CASCADE, related_name='badges', to='core.student')),
            ],
        ),
    ]
