# Generated by Django 4.1.3 on 2023-03-19 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0003_achievement_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='grupo',
            field=models.SlugField(default='default', help_text='Nos permite agrupar varios logros en un grupo (Los que tengan el mismo valor en este campo forman parte del mismo grupo).', max_length=16),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='level',
            field=models.IntegerField(default=1, help_text='Nivel del logro: Sirve tanto para ordenar como para no mostrar logros del mismo grupo pero nivel inferior'),
        ),
    ]
