# Generated by Django 4.1.3 on 2023-03-19 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0004_achievement_grupo_alter_achievement_level'),
    ]

    operations = [
        migrations.RenameField(
            model_name='achievement',
            old_name='grupo',
            new_name='group',
        ),
    ]
